import os
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_anthropic import ChatAnthropic
from langchain_core.output_parsers import CommaSeparatedListOutputParser

# Bootstrapping environment variables from .env file
load_dotenv()

def main():
    if not os.getenv("ANTHROPIC_API_KEY"):
        raise ValueError("CRITICAL: ANTHROPIC_API_KEY not found in environment or .env file.")

    # 1. Initialize the target structural parser
    list_parser = CommaSeparatedListOutputParser()

    # 2. Extract formatting instructions dynamically generated by the parser
    # This automatically injects guidelines telling Claude exactly how to structure the output.
    format_instructions = list_parser.get_format_instructions()
    print("--- Automatically Generated Format Instructions ---")
    print(format_instructions)
    print("---------------------------------------------------\n")

    # 3. Create a template that includes the formatting instructions
    seo_template = (
        "You are an SEO automation engine. Generate a list of exactly 5 highly relevant "
        "search terms and keywords for the following target topic: {topic}.\n"
        "Return ONLY the requested list items, separated exactly as instructed below. "
        "Do not include introduction text or preamble.\n"
        "{format_instructions}"
    )
    
    seo_prompt = PromptTemplate(
        template=seo_template,
        input_variables=["topic"],
        partial_variables={"format_instructions": format_instructions}
    )

    # 4. Bind the model and build the pipeline
    # Using Claude 3.5 Haiku here as it's faster and highly performant for quick structured actions.
    model = ChatAnthropic(model="claude-sonnet-4-5", temperature=0.0) # 0.0 minimizes unexpected formatting changes
    
    # Text flows from prompt to model, then the parser converts the string into a Python list
    seo_chain = seo_prompt | model | list_parser

    # 5. Execute the pipeline
    target_topic = "Serverless Cloud Functions"
    print(f"Processing structural keyword extraction for: '{target_topic}'...")
    
    structured_output = seo_chain.invoke({"topic": target_topic})
    
    print("\n=== PARSED PROGRAMMATIC DATA ===")
    print(f"Returned Data Type : {type(structured_output)}")
    print(f"Total Elements     : {len(structured_output)}")
    print(f"List Contents      : {structured_output}")
    
    # Show that it works as a standard iterable Python list
    print("\nIterating through items:")
    for idx, keyword in enumerate(structured_output, start=1):
        print(f"  {idx}. {keyword.strip()}")
    print("================================\n")

if __name__ == "__main__":
    main()
